export const COLORS = {
  primary: '#10b981',
  primaryLight: '#34d399',
  primaryExtraLight: '#E8F5E9',
  secondary: '#0288D1',
  accent: '#EBFFF1',
  background: '#FAFBFC',
  white: '#FFFFFF',
  text: '#1F2937',
  textLight: '#6B7280',
  textExtraLight: '#9CA3AF',
  error: '#EF4444',
  success: '#10B981',
  warning: '#F59E0B',
  border: '#F3F4F6',
  cardShadow: 'rgba(0,0,0,0.05)',
};

export const HINDI_TEXT = {
  appName: 'KisanVoice AI',
  welcome: 'नमस्ते / Welcome',
  tagline: 'आपका डिजिटल खेती सहायक',
  hindi: 'हिन्दी',
  english: 'English',
  getStarted: 'शुरू करें / Get Started',
  permissionsTitle: 'Permissions we need to help you',
  microphone: 'Microphone / माइक्रोफोन',
  microphoneDesc: 'बोलकर सवाल पूछने के लिए (Ask questions by speaking)',
  location: 'Location / स्थान',
  locationDesc: 'पास की मंडी और मौसम के लिए (For local market & weather)',
  camera: 'Camera / कैमरा',
  cameraDesc: 'फसल की बीमारी जांचने के लिए (To check crop diseases)',
  worksOffline: 'WORKS WITHOUT INTERNET / बिना इंटरनेट के काम करता है',
  login: 'लॉगिन / Login',
  signup: 'साइन अप / Sign Up',
  phoneNumber: 'फोन नंबर / Phone Number',
  enterPhone: 'अपना फोन नंबर दर्ज करें',
  sendOTP: 'OTP भेजें / Send OTP',
  enterOTP: 'OTP दर्ज करें / Enter OTP',
  verify: 'सत्यापित करें / Verify',
  resendOTP: 'OTP फिर से भेजें',
  name: 'नाम / Name',
  enterName: 'अपना नाम दर्ज करें',
  village: 'गांव / Village',
  enterVillage: 'अपना गांव दर्ज करें',
  alreadyHaveAccount: 'पहले से खाता है? लॉगिन करें',
  dontHaveAccount: 'खाता नहीं है? साइन अप करें',
};
